name: 'O-MVLL NDK'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: O-MVLL Android NDK r26d
        shell: bash
        run: |
          curl -LO https://open-obfuscator.build38.io/static/omvll-deps-ndk-r26d.tar
          mkdir -p /tmp/third-party-ndk26
          tar xvf ./omvll-deps-ndk-r26d.tar --directory=/tmp/third-party-ndk26
          curl -LO https://www.python.org/ftp/python/3.10.7/Python-3.10.7.tgz
          tar xzvf Python-3.10.7.tgz --directory=${{ github.workspace }}/dist
          docker run --rm \
            -v /tmp/third-party-ndk26:/third-party \
            -v ${{ github.workspace }}/dist/Python-3.10.7:/Python-3.10.7 \
            -v $GITHUB_WORKSPACE:/o-mvll \
            openobfuscator/omvll-build:latest bash /o-mvll/scripts/docker/ndk_r26_compile.sh
      - name: Upload NDK artifact to latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          prerelease: true
          make_latest: true
          files: |
            ${{ github.workspace }}/dist/omvll-ndk.so
          overwrite_files: true
