name: 'O-MVLL Xcode'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: O-MVLL Build Plugins
        shell: bash
        run: |
          curl -LO https://open-obfuscator.build38.io/static/omvll-v1.4.0-macos-deps.tar
          mkdir -p /tmp/third-party-xcode16
          tar xvf ./omvll-v1.4.0-macos-deps.tar --directory=/tmp/third-party-xcode16
          docker run --rm \
            -v /tmp/third-party-xcode16/omvll-v1.4.0-macos-deps:/deps \
            -v $GITHUB_WORKSPACE:/o-mvll \
            openobfuscator/omvll-build:latest bash /o-mvll/scripts/docker/xcode_16_compile.sh
      - name: Prepare artifacts
        shell: bash
        run: |
          cp ${{ github.workspace }}/src/build_xcode/omvll-xcode_unsigned.dylib \
             ${{ github.workspace }}/src/build_xcode/omvll-xcode.dylib
          cp ${{ github.workspace }}/src/build_xcode/omvll-ndk_unsigned.dylib \
             ${{ github.workspace }}/src/build_xcode/omvll-ndk.dylib
      - name: Upload Xcode artifacts to latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          prerelease: true
          make_latest: true
          files: |
            ${{ github.workspace }}/src/build_xcode/omvll-xcode.dylib
            ${{ github.workspace }}/src/build_xcode/omvll-ndk.dylib
          overwrite_files: true
